---
data:
  raw_data_path: /path/to/parent_dir
  processed_data_path: D://m3cv_testfolder//data
  extraction:
    walk_source_dir: true
    strictUIDs: false
    anon: true
    modalities:
      - ct
      - dose
      - roi:
        - ptv
        - parotid_r
        - parotid_l
    fuzzymatch_ROInames: False
    supplemental_data:
      eortc_qol: /path/to/QOLsurvey.csv
      clinical: /path/to/clinical_patient_db.csv
    date_handling: relative
    anchor_date: RT Completion Date  

  preprocessing:
    static:
      # static preprocessing occurs during data packing and is irreversible
      pixel_size: 2
      crop: [90,128,128]
      center_on: parotid_r
      augmentation: null

    dynamic:
      # dynamic preprocessing occurs on data load and can be changed as desired
      window_level: [400,50]
      ipsi_contra: standardize # other options: null, duplicate
      modalities:
        - ct
        - dose
        - roi:
          - ptv
      supplemental:
        clinical:
          - age at diagnosis
          - marital status
          - gender
          - height (cm)
          - weight (kg)
          - t stage clinical
          - n stage
          - disease site
          - treatment type
          - unlilateral or bilateral
          - hpv status
          - alcohol consumption
          - currently smoke
      endpoint:
        description: overall survival
        type: classification # other option segmentation. regression supported soon
        classify_logic:
          positive:
            clinical:
              Date of Death: '< 730'
          negative:
            clinical:
              Date of Last Follow Up: '>= 730' # Date of Death: null
        segment_target: null # only used for segmentation
    augmentation:
      zoom: 0.2
      rotate: 15
      shift: 0.2
    

  runtime:
    seed: 42
    class_balance: false
    holdout: false
    preload: false
    stratify: true
    kfolds: 10
    val_split: 0.1
    test_split: null
    test_fold: 1

model:
  name: resnet-18
  path_to_custom_model: null
  artifact_output: D://m3cv_testfolder//artifacts

  build_args:
    basefilters: 16
    fusion: true
    fusion_point: early
    # input shape and output shape inferred
    optimizer: adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics:
      - AUC
      - binary_accuracy

  train_args:
    epochs: 10
    batch_size: 4
    class_weight:
      0: 0.5
      1: 1.0
    verbose: 1
    early_stopping: 50

  evaluation:
    binarize_threshold: 0.5
    metrics:
      - accuracy
      - precision
      - recall
      - AUC ROC
      - confusion matrix
...